version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server:21.3.20-alpine
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/etc/clickhouse-server:rw
      - ./log:/var/log/clickhouse-server
      - ./data:/var/lib/clickhouse:rw


