#filebeat.inputs: 
#- type: log
#  enabled: true
#  paths:
#  - /var/lib/docker/containers/*/*.log

filebeat.autodiscover:
  providers:
  - type: docker
    templates:
    - condition:
        contains:
          docker.container.image: collector
      config:
      - type: container
        paths:
        - /var/lib/docker/containers/${data.docker.container.id}/*.log
        exclude_lines: ["^\\s+[\\-`('.|_]"]
        multiline:
          pattern: '^\['
          negate: true
          match: after
          max_lines: 500
          timeout: 2s

output.elasticsearch:
  hosts: '192.168.1.201:9200'