version: '3.1'

services:
  all-in-one:
    image: jaegertracing/all-in-one:1.17
    restart: always
    container_name: jaeger-all-in-one
    env_file:
      - env
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

