version: '3.1'

services:
  nginx:
    image: nginx:1.15.4
    restart: always
    container_name: nginx_1.15.4
    env_file:
      - env
    ports:
      - "80:80"
    volumes:
      - "./logs:/var/log/nginx"
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/conf.d:/etc/nginx/conf.d"
