version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: always
    container_name: elasticsearch
    env_file:
      - elasticsearch_env
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
    - "./data:/data"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    restart: always
    container_name: kibana
    env_file:
      - kibana_env
    ports:
      - " 5601:5601"

    volumes:
    - "./data:/data"
  filebeat:
    image: elastic/filebeat:7.5.1
    restart: always
    container_name: filebeat
    env_file:
      - filebeat_env
    volumes:
    - "./filebeat.conf/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"





