version: '3.1'

services:
  zookeeper:
    image: tylitianrui/zookeeper:3.4.14
    restart: always
    container_name: zookeeper-for-kafka
    env_file:
      - env
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    container_name: kafka
    env_file:
        - env
    ports:
        - "9092:9092"
    links:
        - zookeeper



